### ISSUE TITLE
Save build output to git

### ISSUE THREAD

**Issue by DanielHeath** [tbd-ci/tbd-old#7]
http://git-scm.com/book/en/v2/Git-Internals-Plumbing-and-Porcelain

**Comment by DanielHeath** [comment]
We'll need to write something which runs a build, captures STDOUT/STDERR, then stores each in git (by piping into `git hash-object -w --stdin` and then invoking `git update-ref refs/builds/foo/bar <new_hash>`)

**Comment by DanielHeath** [comment]
Saving the state of the workdir will be easier if we fiddle with `GIT_INDEX_FILE` then call `git-write-tree`

**Comment by DanielHeath** [comment]
Bash script to wire up stdout/stderr stuff:

```
export GIT_INDEX_FILE=/tmp/tbd_index 
git add -A .
git update-ref refs/builds/spec/$(git write-tree)/stdout $(./.tbd/spec/run 2>&1| git hash-object -w --stdin)
```

**Comment by DanielHeath** [comment]
That was actually pretty easy, see a24676fecddca2f6be86d86a892112064a495db3

**Comment by DanielHeath** [comment]
Final step - in `.git/config`, update your remote to sync the new refs:

```
[remote "origin"]
    url = git@github.com:DanielHeath/minecraft-overviewer.git
    fetch = +refs/heads/*:refs/remotes/origin/*
    fetch = +refs/remotes/origin/builds/*:refs/builds/*
    push = +refs/builds/*:refs/remotes/origin/builds/*
```

**Comment by JimGaylard** [comment]
Nice. I like the way you wrote stdout/stderr/combined.
